/*
 * Timer: The timer class
 * Copyright (C) 2006-2007  2015 Burntjam
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * ServicePK.java
 */

package com.rift.coad.daemon.servicebroker.db;

/**
 * ServicePK generated by hbm2java
 */
public class ServicePK  implements java.io.Serializable {

    // Fields    

     private String jndi;
     private String service;

     // Constructors

    /** default constructor */
    public ServicePK() {
    }

    /** full constructor */
    public ServicePK(String jndi, String service) {
       this.jndi = jndi;
       this.service = service;
    }
    
   
    // Property accessors
    public String getJndi() {
        return this.jndi;
    }
    
    public void setJndi(String jndi) {
        this.jndi = jndi;
    }
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }




}


