package com.rift.coad.daemon.messageservice.db;
// Generated Feb 19, 2007 7:55:38 AM by Hibernate Tools 3.2.0.beta6a


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {

    // Fields    

     private String id;
     private String messageCreator;
     private String sessionId;
     private int messageType;
     private int messageRoutingType;
     private int priority;
     private String target;
     private int reply;
     private String fromUrl;
     private String replyUrl;
     private String targetNamedQueue;
     private String replyNamedQueue;
     private String correlationId;
     private int acknowledged;
     private int messageState;
     private Timestamp created;
     private int retries;
     private Timestamp processed;
     private Timestamp nextProcess;
     private Set<MessageError> messageErrors = new HashSet<MessageError>(0);
     private Set<MessageService> messageServices = new HashSet<MessageService>(0);
     private MessageRpcBody messageRpcBody;
     private MessageTxtBody messageTxtBody;
     private Set<MessagePrincipal> messagePrincipals = new HashSet<MessagePrincipal>(0);
     private Set<MessageProperty> messageProperties = new HashSet<MessageProperty>(0);
     private MessageQueue messageQueue;

     // Constructors

    /** default constructor */
    public Message() {
    }

	/** minimal constructor */
    public Message(String id, String messageCreator, String sessionId, int messageType, int messageRoutingType, int priority, int reply, String fromUrl, int acknowledged, int messageState, int retries) {
        this.id = id;
        this.messageCreator = messageCreator;
        this.sessionId = sessionId;
        this.messageType = messageType;
        this.messageRoutingType = messageRoutingType;
        this.priority = priority;
        this.reply = reply;
        this.fromUrl = fromUrl;
        this.acknowledged = acknowledged;
        this.messageState = messageState;
        this.retries = retries;
    }
    /** full constructor */
    public Message(String id, String messageCreator, String sessionId, int messageType, int messageRoutingType, int priority, String target, int reply, String fromUrl, String replyUrl, String targetNamedQueue, String replyNamedQueue, String correlationId, int acknowledged, int messageState, Timestamp created, int retries, Timestamp processed, Timestamp nextProcess, Set<MessageError> messageErrors, Set<MessageService> messageServices, MessageRpcBody messageRpcBody, MessageTxtBody messageTxtBody, Set<MessagePrincipal> messagePrincipals, Set<MessageProperty> messageProperties, MessageQueue messageQueue) {
       this.id = id;
       this.messageCreator = messageCreator;
       this.sessionId = sessionId;
       this.messageType = messageType;
       this.messageRoutingType = messageRoutingType;
       this.priority = priority;
       this.target = target;
       this.reply = reply;
       this.fromUrl = fromUrl;
       this.replyUrl = replyUrl;
       this.targetNamedQueue = targetNamedQueue;
       this.replyNamedQueue = replyNamedQueue;
       this.correlationId = correlationId;
       this.acknowledged = acknowledged;
       this.messageState = messageState;
       this.created = created;
       this.retries = retries;
       this.processed = processed;
       this.nextProcess = nextProcess;
       this.messageErrors = messageErrors;
       this.messageServices = messageServices;
       this.messageRpcBody = messageRpcBody;
       this.messageTxtBody = messageTxtBody;
       this.messagePrincipals = messagePrincipals;
       this.messageProperties = messageProperties;
       this.messageQueue = messageQueue;
    }
    
   
    // Property accessors
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getMessageCreator() {
        return this.messageCreator;
    }
    
    public void setMessageCreator(String messageCreator) {
        this.messageCreator = messageCreator;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public int getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(int messageType) {
        this.messageType = messageType;
    }
    public int getMessageRoutingType() {
        return this.messageRoutingType;
    }
    
    public void setMessageRoutingType(int messageRoutingType) {
        this.messageRoutingType = messageRoutingType;
    }
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }
    public String getTarget() {
        return this.target;
    }
    
    public void setTarget(String target) {
        this.target = target;
    }
    public int getReply() {
        return this.reply;
    }
    
    public void setReply(int reply) {
        this.reply = reply;
    }
    public String getFromUrl() {
        return this.fromUrl;
    }
    
    public void setFromUrl(String fromUrl) {
        this.fromUrl = fromUrl;
    }
    public String getReplyUrl() {
        return this.replyUrl;
    }
    
    public void setReplyUrl(String replyUrl) {
        this.replyUrl = replyUrl;
    }
    public String getTargetNamedQueue() {
        return this.targetNamedQueue;
    }
    
    public void setTargetNamedQueue(String targetNamedQueue) {
        this.targetNamedQueue = targetNamedQueue;
    }
    public String getReplyNamedQueue() {
        return this.replyNamedQueue;
    }
    
    public void setReplyNamedQueue(String replyNamedQueue) {
        this.replyNamedQueue = replyNamedQueue;
    }
    public String getCorrelationId() {
        return this.correlationId;
    }
    
    public void setCorrelationId(String correlationId) {
        this.correlationId = correlationId;
    }
    public int getAcknowledged() {
        return this.acknowledged;
    }
    
    public void setAcknowledged(int acknowledged) {
        this.acknowledged = acknowledged;
    }
    public int getMessageState() {
        return this.messageState;
    }
    
    public void setMessageState(int messageState) {
        this.messageState = messageState;
    }
    public Timestamp getCreated() {
        return this.created;
    }
    
    public void setCreated(Timestamp created) {
        this.created = created;
    }
    public int getRetries() {
        return this.retries;
    }
    
    public void setRetries(int retries) {
        this.retries = retries;
    }
    public Timestamp getProcessed() {
        return this.processed;
    }
    
    public void setProcessed(Timestamp processed) {
        this.processed = processed;
    }
    public Timestamp getNextProcess() {
        return this.nextProcess;
    }
    
    public void setNextProcess(Timestamp nextProcess) {
        this.nextProcess = nextProcess;
    }
    public Set<MessageError> getMessageErrors() {
        return this.messageErrors;
    }
    
    public void setMessageErrors(Set<MessageError> messageErrors) {
        this.messageErrors = messageErrors;
    }
    public Set<MessageService> getMessageServices() {
        return this.messageServices;
    }
    
    public void setMessageServices(Set<MessageService> messageServices) {
        this.messageServices = messageServices;
    }
    public MessageRpcBody getMessageRpcBody() {
        return this.messageRpcBody;
    }
    
    public void setMessageRpcBody(MessageRpcBody messageRpcBody) {
        this.messageRpcBody = messageRpcBody;
    }
    public MessageTxtBody getMessageTxtBody() {
        return this.messageTxtBody;
    }
    
    public void setMessageTxtBody(MessageTxtBody messageTxtBody) {
        this.messageTxtBody = messageTxtBody;
    }
    public Set<MessagePrincipal> getMessagePrincipals() {
        return this.messagePrincipals;
    }
    
    public void setMessagePrincipals(Set<MessagePrincipal> messagePrincipals) {
        this.messagePrincipals = messagePrincipals;
    }
    public Set<MessageProperty> getMessageProperties() {
        return this.messageProperties;
    }
    
    public void setMessageProperties(Set<MessageProperty> messageProperties) {
        this.messageProperties = messageProperties;
    }
    public MessageQueue getMessageQueue() {
        return this.messageQueue;
    }
    
    public void setMessageQueue(MessageQueue messageQueue) {
        this.messageQueue = messageQueue;
    }




}


