package com.rift.coad.daemon.messageservice.db;
// Generated Feb 19, 2007 7:55:38 AM by Hibernate Tools 3.2.0.beta6a



/**
 * MessageQueueService generated by hbm2java
 */
public class MessageQueueService  implements java.io.Serializable {

    // Fields    

     /**
      * 		       auto_increment
 * 		    
     */
     private Integer id;
     private String service;
     private MessageQueue messageQueue;

     // Constructors

    /** default constructor */
    public MessageQueueService() {
    }

	/** minimal constructor */
    public MessageQueueService(String service) {
        this.service = service;
    }
    /** full constructor */
    public MessageQueueService(String service, MessageQueue messageQueue) {
       this.service = service;
       this.messageQueue = messageQueue;
    }
    
   
    // Property accessors
    /**       
     *      * 		       auto_increment
     * 		    
     */
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }
    public MessageQueue getMessageQueue() {
        return this.messageQueue;
    }
    
    public void setMessageQueue(MessageQueue messageQueue) {
        this.messageQueue = messageQueue;
    }




}


