package com.rift.coad.daemon.messageservice.db;
// Generated Feb 19, 2007 7:55:38 AM by Hibernate Tools 3.2.0.beta6a



/**
 * MessageRpcBody generated by hbm2java
 */
public class MessageRpcBody  implements java.io.Serializable {

    // Fields    

     private String messageId;
     private String xml;
     private Integer generatedException;
     private byte[] resultValue;
     private byte[] exceptionValue;
     private Message message;

     // Constructors

    /** default constructor */
    public MessageRpcBody() {
    }

	/** minimal constructor */
    public MessageRpcBody(String messageId, String xml, Message message) {
        this.messageId = messageId;
        this.xml = xml;
        this.message = message;
    }
    /** full constructor */
    public MessageRpcBody(String messageId, String xml, Integer generatedException, byte[] resultValue, byte[] exceptionValue, Message message) {
       this.messageId = messageId;
       this.xml = xml;
       this.generatedException = generatedException;
       this.resultValue = resultValue;
       this.exceptionValue = exceptionValue;
       this.message = message;
    }
    
   
    // Property accessors
    public String getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }
    public String getXml() {
        return this.xml;
    }
    
    public void setXml(String xml) {
        this.xml = xml;
    }
    public Integer getGeneratedException() {
        return this.generatedException;
    }
    
    public void setGeneratedException(Integer generatedException) {
        this.generatedException = generatedException;
    }
    public byte[] getResultValue() {
        return this.resultValue;
    }
    
    public void setResultValue(byte[] resultValue) {
        this.resultValue = resultValue;
    }
    public byte[] getExceptionValue() {
        return this.exceptionValue;
    }
    
    public void setExceptionValue(byte[] exceptionValue) {
        this.exceptionValue = exceptionValue;
    }
    public Message getMessage() {
        return this.message;
    }
    
    public void setMessage(Message message) {
        this.message = message;
    }




}


