package com.rift.coad.hibernate.util.test;
// Generated Jan 12, 2007 7:23:41 AM by Hibernate Tools 3.2.0.beta6a


import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by hbm2java
 */
public class Test  implements java.io.Serializable {

    // Fields    

     private String id;
     
     // Constructors

    /** default constructor */
    public Test() {
    }
    
    /** minimal constructor */
    public Test(String id) {
        this.id = id;
    }
    
   
    // Property accessors
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
}
    