package com.rift.coad.daemon.messageservice.db;
// Generated Feb 19, 2007 7:55:38 AM by Hibernate Tools 3.2.0.beta6a



/**
 * MessageTxtBody generated by hbm2java
 */
public class MessageTxtBody  implements java.io.Serializable {

    // Fields    

     private String messageId;
     private String body;
     private Message message;

     // Constructors

    /** default constructor */
    public MessageTxtBody() {
    }

    /** full constructor */
    public MessageTxtBody(String messageId, String body, Message message) {
       this.messageId = messageId;
       this.body = body;
       this.message = message;
    }
    
   
    // Property accessors
    public String getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public Message getMessage() {
        return this.message;
    }
    
    public void setMessage(Message message) {
        this.message = message;
    }




}


