package com.rift.coad.daemon.messageservice.db;
// Generated Feb 19, 2007 7:55:38 AM by Hibernate Tools 3.2.0.beta6a



/**
 * MessagePrincipal generated by hbm2java
 */
public class MessagePrincipal  implements java.io.Serializable {

    // Fields    

     /**
      * 		       auto_increment
 * 		    
     */
     private Integer id;
     private String principalValue;
     private Message message;

     // Constructors

    /** default constructor */
    public MessagePrincipal() {
    }

	/** minimal constructor */
    public MessagePrincipal(String principalValue) {
        this.principalValue = principalValue;
    }
    /** full constructor */
    public MessagePrincipal(String principalValue, Message message) {
       this.principalValue = principalValue;
       this.message = message;
    }
    
   
    // Property accessors
    /**       
     *      * 		       auto_increment
     * 		    
     */
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPrincipalValue() {
        return this.principalValue;
    }
    
    public void setPrincipalValue(String principalValue) {
        this.principalValue = principalValue;
    }
    public Message getMessage() {
        return this.message;
    }
    
    public void setMessage(Message message) {
        this.message = message;
    }




}


