package com.rift.coad.daemon.messageservice.db;
// Generated Feb 19, 2007 7:55:38 AM by Hibernate Tools 3.2.0.beta6a



/**
 * MessageService generated by hbm2java
 */
public class MessageService  implements java.io.Serializable {

    // Fields    

     /**
      * 		       auto_increment
 * 		    
     */
     private Integer id;
     private String service;
     private Message message;

     // Constructors

    /** default constructor */
    public MessageService() {
    }

	/** minimal constructor */
    public MessageService(String service) {
        this.service = service;
    }
    /** full constructor */
    public MessageService(String service, Message message) {
       this.service = service;
       this.message = message;
    }
    
   
    // Property accessors
    /**       
     *      * 		       auto_increment
     * 		    
     */
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }
    public Message getMessage() {
        return this.message;
    }
    
    public void setMessage(Message message) {
        this.message = message;
    }




}


